# Welcome to Jekyll!
#

# Site settings
title: Seunghyeong Yu
description: |
  I'm currently studying  
  wireless communications at [IWCL](https://sites.google.com/view/iwcl)
owner: Seunghyeong Yu # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: seunghy@unist.ac.kr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seunghy1468.github.io/" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/seunghy1468/
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/seunghyeong.yu
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: seunghy@unist.ac.kr #/contact/
  #flickr:
  instagram: https://www.instagram.com/gabriel_yu__/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
